### ISSUE TITLE
Support for WP 5.7.2

### ISSUE THREAD

**Issue by banna360** [wikitribune/fabrica-pending-revisions#1]
I tried to installed in on WP 5.7.2. I dont see any option or settings. Will it support 5.7.2?

**Comment by andrewstaffell** [comment]
WordPress 5 is not supported I'm afraid. The plugin was developed for WordPress 4, but then WikiTribune switched to a bespoke platform (ie. not WP-based) so development was discontinued. 

You could check out [PublishPress Revisions](https://wordpress.org/plugins/revisionary/) which has similar functionality and WP 5 compatible.
